name: Dependencies Audit

on: [push]

jobs:
  lint:
    name: Dependencies Audit
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 14.x
    - name: Perform audit
      run: npm audit
      working-directory: app