name: Lint Check

on: [push]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.1.2 
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm install
      working-directory: app
    - name: Lint Check
      run: ./node_modules/.bin/eslint src/
      working-directory: app