name: Publish Image Using Tag Name

on:
  push:
    tags:        
      - v*

jobs:
  push:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Push the image on the registry
      uses: Ferlab-Ste-Justine/action-push-image@master
      with:
        username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
        password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
        image: ferlabcrsj/git-autosync
        tag_source: ref
        location: app
        dockerfile: app/Dockerfile